language: python
cache: pip

branches:
  except:
      - /^[^/]+/.+$/
      - book
      - /^book/.+$/

python:
  - "3.6"

env:
  - MONGODB_VERSION=4.0.8
  - MONGODB_VERSION=3.6.11
  - MONGODB_VERSION=3.4.7

matrix:
  include:
    - python: "3.6"
      env: MONGODB_VERSION=3.4.4 NO_PYTZ=1
    - python: "3.6"
      env: MONGODB_VERSION=3.2.22
    - python: "3.6"
      env: MONGODB_VERSION=4.0.8 FIPS=1 OPENSSL_FIPS=1
    - python: "3.7"
      dist: xenial

before_install:
  - wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-${MONGODB_VERSION}.tgz -O /tmp/mongodb.tgz
  - tar -xvf /tmp/mongodb.tgz
  - mkdir /tmp/data
  - ${PWD}/mongodb-linux-x86_64-${MONGODB_VERSION}/bin/mongod --dbpath /tmp/data --bind_ip 127.0.0.1 --noauth &> /dev/null &

install:
  - 'travis_retry pip install --upgrade setuptools pip pytest pytest-cov codecov "setuptools_scm>=1.9" cffi'
  - 'pip install -e ".[development]"'
  - 'test -z "${FIPS}" && pip install -e ".[development]" || true'
  - 'test -n "${FIPS}" && pip install -e ".[development,fips]" || true'
  - 'test -n "${NO_PYTZ}" && pip uninstall --yes pytz tzlocal || true'

script:
    pytest

after_script:
    bash <(curl -s https://codecov.io/bash)

notifications:
  irc:
    channels:
      - 'irc.freenode.org#webcore'
    use_notice: true
    skip_join: true
    on_success: change
    on_failure: always
    template:
      - "%{repository_slug}:%{branch}@%{commit} %{message}"
      - "Duration: %{duration} - Details: %{build_url}"
