language: python
sudo: false
cache: pip

branches:
  except:
      - /^[^/]+/.+$/
      - book
      - /^book/.+$/

python:
  - "2.7"
  - "pypy-5.4.1"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

env:
  - MONGODB_VERSION=3.4.4

matrix:
  include:
    - python: "3.5"
      env: NO_PYTZ=1 MONGODB_VERSION=3.4.4
    - python: "3.5"
      env: MONGODB_VERSION=3.2.13

before_install:
  - wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-${MONGODB_VERSION}.tgz -O /tmp/mongodb.tgz
  - tar -xvf /tmp/mongodb.tgz
  - mkdir /tmp/data
  - ${PWD}/mongodb-linux-x86_64-${MONGODB_VERSION}/bin/mongod --dbpath /tmp/data --bind_ip 127.0.0.1 --noauth &> /dev/null &

install:
  - 'travis_retry pip install --upgrade setuptools pip pytest pytest-cov codecov "setuptools_scm>=1.9" cffi'
  - 'pip install -e ".[development,logger]"'
  - '[[ -e $NO_PYTZ ]] && pip uninstall --quiet --yes pytz tzlocal'

script:
    python setup.py test

after_script:
    bash <(curl -s https://codecov.io/bash)

notifications:
  irc:
    channels:
      - 'irc.freenode.org#webcore'
    use_notice: true
    skip_join: true
    on_success: change
    on_failure: always
    template:
      - "%{repository_slug}:%{branch}@%{commit} %{message}"
      - "Duration: %{duration} - Details: %{build_url}"
